 version: 2.1

 orbs:
  win: circleci/windows@2.2.0
  slack: circleci/slack@3.4.2
 jobs:
   build:
     executor: win/default     
    
     steps:
       - slack/notify:
          color: '#42e2f4'
          mentions: 'USERID1,USERID2,'
          message: 上傳成功
          webhook: https://hooks.slack.com/services/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
       - slack/status:
          fail_only: true
          mentions: 'USERID1,USERID2'
          webhook: https://hooks.slack.com/services/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
