 version: 2.1

 orbs:
  win: circleci/windows@2.2.0
  slack: circleci/slack@3.4.2
 jobs:
   build:
     executor: win/default     
    
     steps:
      - run:
      - slack/notify:
        color: "red"
        mentions: "yemiwebby,"
        message: 更新 C-Sharp-UnitTest1
