 version: 2.1

 orbs:
  win: circleci/windows@2.2.0
  slack: circleci/slack@3.4.2
 jobs:
   build:
     executor: win/default     
    
     steps:
           - run:
         command: echo hello && echo world
         shell: bash.exe
